[project]
name = "av-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Felipe Braga", email = "felipeluissanchesbraga13@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pymysql>=1.2.3",
    "sqlalchemy>=2.1.4",
]

[project.scripts]
av-5 = "av_5:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
